# Generated by Django 5.0.3 on 2024-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                ("cast_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("DoB", models.DateField()),
                ("Image", models.ImageField(upload_to="")),
            ],
        ),
    ]
