# Generated by Django 5.0.3 on 2024-04-01 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
