# Generated by Django 5.0.3 on 2024-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_cast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='Image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cast',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
