# Generated by Django 5.0.3 on 2024-05-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0004_alter_cast_dob_alter_cast_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
