# Generated by Django 5.0.3 on 2024-05-08 16:34

from django.db import migrations
from django.utils.text import slugify

def add_slug_to_existing_instances(apps, schema_editor):
    MyModel = apps.get_model('myapp', 'MyModel')
    for instance in MyModel.objects.all():
        if not instance.slug:
            instance.slug = slugify(instance.name)
            instance.save()
class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [ migrations.RunPython(add_slug_to_existing_instances),]
