# Generated by Django 5.0.3 on 2024-03-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("movie_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("adventure", "Adventure"),
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("science_fiction", "Science Fiction"),
                            ("fantasy", "Fantasy"),
                            ("romance", "Romance"),
                            ("thriller", "Thriller"),
                            ("documentary", "Documentary"),
                            ("crime", "Crime"),
                            ("mystery", "Mystery"),
                            ("animation", "Animation"),
                            ("family", "Family"),
                            ("biography", "Biography"),
                            ("history", "History"),
                            ("war", "War"),
                            ("musical", "Musical"),
                            ("western", "Western"),
                            ("film_noir", "Film Noir"),
                        ],
                        max_length=255,
                    ),
                ),
                ("discription", models.TextField()),
                ("release_date", models.DateField()),
                ("poster_path", models.ImageField(upload_to="")),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="cast.cast"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("role_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=255)),
                (
                    "cast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="cast.cast"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="movies.movies",
                    ),
                ),
            ],
        ),
    ]
