# Generated by Django 5.0.3 on 2024-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("adventure", "Adventure"),
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("science_fiction", "Science Fiction"),
                            ("fantasy", "Fantasy"),
                            ("romance", "Romance"),
                            ("thriller", "Thriller"),
                            ("documentary", "Documentary"),
                            ("crime", "Crime"),
                            ("mystery", "Mystery"),
                            ("animation", "Animation"),
                            ("family", "Family"),
                            ("biography", "Biography"),
                            ("history", "History"),
                            ("war", "War"),
                            ("musical", "Musical"),
                            ("western", "Western"),
                            ("film_noir", "Film Noir"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="movies",
            name="genre",
        ),
        migrations.AddField(
            model_name="movies",
            name="genre",
            field=models.ManyToManyField(to="movies.genre"),
        ),
    ]
