# Generated by Django 5.0.3 on 2024-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_slug_alter_movies_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(max_length=255),
        ),
    ]
