# Generated by Django 5.0.3 on 2024-05-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_poster_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='discription',
            new_name='description',
        ),
    ]
