# Generated by Django 5.0.3 on 2024-05-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_director_movies_director_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='director_id',
            new_name='director',
        ),
    ]
